name: Update config types

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  update:

    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
        contents: write           # 'write' access to repository contents

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update config types
        run: |
          rm -f stardust-config.d.ts;
          curl https://raw.githubusercontent.com/spaceness/stardust/main/src/types/config.d.ts -o stardust-config.d.ts;
          git add .;
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.repository == 'spaceness/stardust-docs' && github.ref == 'refs/heads/main' }}
        with:
          commit_message: "chore: sync config type"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
